"""empty message

Revision ID: 1d5919ed00b8
Revises: 2bf464a5c748
Create Date: 2014-08-18 19:10:12.641000

"""

# revision identifiers, used by Alembic.
revision = '1d5919ed00b8'
down_revision = '2bf464a5c748'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
