"""empty message

Revision ID: 1ab407986935
Revises: 485a74fe545f
Create Date: 2014-08-13 14:14:26.376000

"""

# revision identifiers, used by Alembic.
revision = '1ab407986935'
down_revision = '485a74fe545f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('likeit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'likeit')
    ### end Alembic commands ###
