"""empty message

Revision ID: 31103d731d3c
Revises: 232d5da4589a
Create Date: 2014-08-06 19:38:35.514000

"""

# revision identifiers, used by Alembic.
revision = '31103d731d3c'
down_revision = '232d5da4589a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
