"""empty message

Revision ID: 48020645b551
Revises: 4fa67dd37fd3
Create Date: 2014-08-08 20:01:19.127000

"""

# revision identifiers, used by Alembic.
revision = '48020645b551'
down_revision = '4fa67dd37fd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
